#!/bin/bash

# ID: Callum Moffat 10367258


# Creating the getprop() function as directed in the task sheet. Within this function I have assigned various variables which will be called upon in the final stage of the code.
getprop() {                                                                                                                               
    
    #For the file size I used the du command to report the disk space used the file ($1/$fname) but the options format it to be accurately stated in bytes (-b) and (-h) to be in a human readable form which formats the bytes into kilobytes.
    #The output of the du command is then piped to a grep which will only grab whole figures or figures with one decimal which is how -h displays the kilobytes. We are excluding the "K" here because in the task sheet it is excluded to outside the variable.
    fsize=$(du -bh $1 | grep -E -o '[0-9]+'.'?[0-9]+')                  
    
    #For the word count I used the wc -w command and option to count only the words within the provided file ($1/$fname), this information is then piped to a similar grep to above which only will grab the word count for us to call on later in our echo statement.
    wcount=$(wc -w $1 | grep -E -o '[0-9]+')

    #Last modified date (lmd) is generated by using the stat command with the format -c %y. This will print out the stat details of the file that are only for the modification date and time.
    #The stat information is then piped through to a grep command which will only grab the date in it's current form of yyyy-mm-dd. This current format of the date is then passed through a sed command which is using "|" as an alternative delimiter and re-formats the date to dd-mm-yyyy via escaped (\) values (3,2,1).
    lmd=$(stat -c %y $1 | grep -E -o '[0-9]{4}'-'[0-9]{2}'-'[0-9]{2}' | sed -E "s|([0-9]{4})-([0-9]{2})-([0-9]{2})|\3-\2-\1|")

    #Last modified time (lmt) is generated by using the same stat command as above but at the grep phase only grabbing the time value in the format of hh:mm:ss
    lmt=$(stat -c %y $1 | grep -E -o '[0-9]{2}':'[0-9]{2}':'[0-9]{2}')

    #Last modified date/time (lmdt) was assigned to combine both the two values created above of lmd and lmt but formatted properly for the echo statement below
    lmdt="$lmd $lmt"

    #echo statement that is calling on the fname value ($1) provided in the read prompt below, the wcount, fsize and lmdt variables that were assigned values above.
    echo -e "\nThe file $1 contains $wcount words and is ${fsize}K in size and was last modified $lmdt\n"
}

#Created an entry statement to explain what the program does, below which is the read command that will collect the file name and assign it to fname. Last call in this section is to call the function getprop and assign it's $1 argument to the user provided $fname.
echo -e "\nHello! This program calculates a file's word count, file size in kilobytes and the date and time the file was last modified!\n"
read -p "Please enter the file name : " fname
getprop $fname

#Exit the program with the correct exit code.
exit 0